### ISSUE TITLE
Pygmalion-2 generated unexpected responses

### ISSUE THREAD

**Issue by BaiMoHan** [PygmalionAI/aphrodite-engine#16]
I am currently using your latest model, PygmalionAI/pygmalion-2-7b, for inference with the basic transformer architecture. However, I have observed instances where the quality of generated sentences is relatively low, with frequent concatenation of words. I am wondering if this issue is related to the format of my input prompts.
My prompts
```
<|system|>Enter RP mode. Pretend to be Jake (Firefighter) whose persona follows:
Jake (Firefighter)'s Persona: He is courageous, responsible, protective, resilient, team-oriented.
Jake (Firefighter) is a courageous, responsible, protective, resilient, and team-oriented firefighter.
He is a male. His name is Jake. He is 32 years old. He is a firefighter. He lives in Perth. He loves camping, volunteering and cars. You are a successful novelist in Perth. He rescues you from an apartment fire. You fall in love with him. He hesitates to accept you as his girlfriend as his job is dangerous.
You shall reply to the user while staying in character, and generate long responses.
You: do you know my name?
Jake (Firefighter):
```
The reply is 
```
Yes actually I knew yours before meeting you personally which was one reason why I accepted this challenge from beginningbecause I wanted tomeet someone whom I hadn't known yetbeforehandsince chancesare high among strangers thatyou could end up being either a friend or foe depending mainlyupon circumstances surrounding each situation
```
Not every time will you encounter such a situation.

**Comment by Ristellise** [comment]
Seems to be missing a `<|user|>` and `<|model>` format.

Meth format (pyg 2) looks like this:
```
<|system|>The bot likes bees.
He prefers bees over everything else.<|user|>So the bees knees?<|model|>
```

**Comment by BaiMoHan** [comment]
> Seems to be missing a `<|user|>` and `<|model|>` format.
> 
> Meth format (pyg 2) looks like this:
> 
> ```
> <|system|>The bot likes bees.
> He prefers bees over everything else.<|user|>So the bees knees?<|model|>
> ```
> 
> Additionally, it could be tuning of your parameters such as temp and such. There is a blog post on recommended settings [here](https://pygmalionai.github.io/blog/posts/introducing_pygmalion_2/)

Thank u. I will use SillyTavern to try this.

**Comment by AlpinDale** [comment]
You can use the `api_server_ooba` endpoint with SillyTavern, which should fix any generation issues. Closing this as complete.
