### ISSUE TITLE
No logits_processors in sampling params

### ISSUE THREAD

**Issue by AWAS666** [PygmalionAI/aphrodite-engine#18]
Has this been removed and left over in the openai endpoint?
https://github.com/PygmalionAI/aphrodite-engine/blob/ca43123a3036244f34b736ca540588415928524e/aphrodite/endpoints/openai/api_server.py#L229

**Comment by AlpinDale** [comment]
#19 should fix this issue, can you please test?

**Comment by AWAS666** [comment]
> > Has this been removed and left over in the openai endpoint?
> > https://github.com/PygmalionAI/aphrodite-engine/blob/ca43123a3036244f34b736ca540588415928524e/aphrodite/endpoints/openai/api_server.py#L229
> 
> Yes, I haven't updated the OpenAI endpoint (and may remove it soon). For now, I can make a quick update to fix this issue.

Remove the logit_processor or the openai api?
I just gave it a spin on my fork where I just deleted it and it does output, but there seem to be some other issues, not sure if model related so I'll try another one, tried [this](https://huggingface.co/TheBloke/llama2_70b_chat_uncensored-AWQ)

But I'll test yours and also download another model to check.
