### ISSUE TITLE
Add RoPE scaling arguments to engine

### ISSUE THREAD

**Issue by AlpinDale** [PygmalionAI/aphrodite-engine#220]
Currently, we auto-scale using the `--max-model-len` argument. It may be more appropriate to have specific options for the scaling factor, etc.

**Comment by sparsh35** [comment]
Hi getting error for bigger context models like Microsoft Phi 3 medium with respect to rope scaling factors with exl2 format.

**Comment by sparsh35** [comment]
It is something related to this I think, maybe not much needs to be done here, just implement this code , I will try to test if it doesn't breaks anything else , here is the git in vllm for this feature https://github.com/vllm-project/vllm/pull/4638

**Comment by sparsh35** [comment]
https://github.com/vllm-project/vllm/pull/4298 vllm has implemented rotatry scale embeddings like this

**Comment by AlpinDale** [comment]
Added in v0.6.0.
