### ISSUE TITLE
Set ooba API Key as argument

### ISSUE THREAD

**Issue by miku448** [PygmalionAI/aphrodite-engine#30]
I'm using the `aphrodite-engine` pip package directly from the release tag without building it on my own. Thus, I'm unable to set a custom API Key to the ooba endpoint since it's on the source code.

Would it make sense to overwrite it with an argument or directly an env variable?
```
python -m aphrodite.endpoints.api_server_ooba --api-key <MY_API_KEY>
# or it also could be
API_KEY=<MY_API_KEY> python -m aphrodite.endpoints.api_server_ooba
```

**Comment by AlpinDale** [comment]
This is definitely on the TODO list to be implemented ASAP. I'll likely use an environment variable for now, and then switch to passing a list of keys with an arg.

**Comment by AlpinDale** [comment]
@miku448 small update, we're currently working on a more robust API system. But for now, you can install the pip package but launch the api by running a modified `api_server_ooba.py` script with your custom API key(s).

**Comment by miku448** [comment]
@AlpinDale Sure! that works for now. This is more of a nice to have so it's not a big issue actually.
Looking forward for those updates!

**Comment by AlpinDale** [comment]
@miku448 the ooba endpoint (`aphrodite.endpoints.ooba.api_server`) now supports the `--api-keys` flag, which can take a list of valid API keys. It will be included in the next release in a few hours.

**Comment by AlpinDale** [comment]
Added to the latest release.
