### ISSUE TITLE
Configuration of the internal port of the docker container

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#300]
Hi, nice and great Job, im wondering if you can add something like this:

```
echo 'Starting Aphrodite Engine API server...'

CMD="python3 -m aphrodite.endpoints.${ENDPOINT:-openai}.api_server
             --host 0.0.0.0
             ${SELECTED_PORT:+--port $SELECTED_PORT}
             --download-dir ${HF_HOME}
```

in certains scenarios with multiple instances of the engine it will be usefull to control the internal listening port of the container.

Regards!

**Comment by puppetm4st3r** [comment]
also will be very useful to install the hf_transfer package inside de image in order to download at the speed of the light, in my case I can get 3x speed in optics fiber when use the hf_transfer by the -e HF_HUB_ENABLE_HF_TRANSFER="true" env var in a modified container with that package.

regards!

**Comment by AlpinDale** [comment]
This was fixed yesterday, PORT should be a configurable env variable now.

**Comment by puppetm4st3r** [comment]
thaaaanks!
