### ISSUE TITLE
GGUF IQ quants support

### ISSUE THREAD

**Issue by sorasoras** [PygmalionAI/aphrodite-engine#306]
Does aphrodite support new IQ series quants?
  19  or  IQ2_XXS :  2.06 bpw quantization
  20  or  IQ2_XS  :  2.31 bpw quantization
  28  or  IQ2_S   :  2.5  bpw quantization
  29  or  IQ2_M   :  2.7  bpw quantization
  24  or  IQ1_S   :  1.56 bpw quantization
  23  or  IQ3_XXS :  3.06 bpw quantization
  26  or  IQ3_S   :  3.44 bpw quantization
  27  or  IQ3_M   :  3.66 bpw quantization mix
  22  or  IQ3_XS  :  3.3 bpw quantization
  25  or  IQ4_NL  :  4.50 bpw non-linear quantization
  30  or  IQ4_XS  :  4.25 bpw non-linear quantization

There are lots of new one.

**Comment by AlpinDale** [comment]
I have [a branch](https://github.com/PygmalionAI/aphrodite-engine/tree/feat/imatrix-gguf) to support the new ones, I'll finish it up soon. For now, you can use exllamav2 quants - they support arbitrary precision.
