### ISSUE TITLE
Prompts are being interpolated on log output

### ISSUE THREAD

**Issue by fullstackwebdev** [PygmalionAI/aphrodite-engine#309]
```

Traceback (most recent call last):
  File "/home/shazam/.local/lib/python3.9/site-packages/loguru/_handler.py", line 136, in emit
    formatted = precomputed_format.format_map(formatter_record)
KeyError: 'input_text'
--- End of logging error ---
INFO:     Finished request cmpl-67fcb6407f034ffe9e354df8765e9d72.
INFO:     ::1:56946 - "POST /v1/chat/completion

```

I saw this on my screen. My few shot prompt contains ${input_text}.  For whatever reason, loguru is trying to interpolate it, and when it can't it fails.

**Comment by AlpinDale** [comment]
Yeah unfortunately, loguru is being a pain about this. It doesn't escape by default, and the rich.escape module doesn't escape everything. You can try `--max-log-len 0` to disable printing prompts. We're (along with [tabbyAPI](https://github.com/theroyallab/tabbyAPI)) currently trying to figure out a fix for this.

**Comment by fschuh** [comment]
I'm also having this error.
Why close the issue if the error is still not resolved?
