### ISSUE TITLE
Load part of GGUF to GPU and CPU? 

### ISSUE THREAD

**Issue by CHesketh76** [PygmalionAI/aphrodite-engine#314]
Just wondering if this was possible and if there was an example of how to do it.

**Comment by AlpinDale** [comment]
Unfortunately partial offloading to CPU is currently not possible. CPU-only is doable (albeit not at the same level of performance as llama.cpp), but splitting the ops between GPU and CPU would be a significant modification to the engine. Currently not planned. 

CPU-only is currently a work in progress, but it's intended to be used for development purposes.
