### ISSUE TITLE
[Bug]: Pydantic serializer issue when pinging /v1/models

### ISSUE THREAD

**Issue by AlpinDale** [PygmalionAI/aphrodite-engine#324]
### Your current environment

N/A

### 🐛 Describe the bug

When sending a GET request to the `/v1/models` endpoint for the first time, it'll output a pydantic serializer warning, with no tracebacks:

```
/home/anon/.local/lib/python3.10/site-packages/pydantic/main.py:314: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `bool` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

Can't think of why this happens.

**Comment by v151bl35p3ctrum** [comment]
I am encountering this same exact issue.

**Comment by AlpinDale** [comment]
Fixed, seems like we had the `is_blocking` set to a string instead of bool in `ModelPermission` pydantic model. Fix is merged in dev.
