### ISSUE TITLE
[Bug]: exl2 is not auto detected

### ISSUE THREAD

**Issue by nivibilla** [PygmalionAI/aphrodite-engine#331]
### Your current environment

N/A

### 🐛 Describe the bug

Loading without specifying `--quantization exl2` tries to load the model with quantisation mode `None`. Manually specifying that it is an exl2 quant works.

**Comment by AlpinDale** [comment]
Unfortunately, it's a bit difficult to auto-detect exl2 - it's the only quant format that does not ship a quantization config file, so the guesswork won't always work. I requested turboderp to have exl2 quants ship the config too, and it seems [he's doing that now](https://github.com/turboderp/exllamav2/commit/5fb2c679cb7f81c9811e24ab1362f2436e1b5546). Future exl2 quants shouldn't have this problem, hopefully.

**Comment by nivibilla** [comment]
Ah okay np. Thanks for the quick reply!
