### ISSUE TITLE
[Feature]: Support YiForCausalLM

### ISSUE THREAD

**Issue by gsuhm** [PygmalionAI/aphrodite-engine#348]
### 🚀 The feature, motivation and pitch

would love to run Yi models :-)

**Comment by AlpinDale** [comment]
Hi, Yi is already supported.

**Comment by gsuhm** [comment]
running 0.5.1 I got this:  

    raise ValueError(
ValueError: Model architectures ['YiForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OLMoForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM']

**Comment by AlpinDale** [comment]
All the official Yi models have been llama-fied, which model are you using? I can give it a try.

**Comment by gsuhm** [comment]
Might not be an official model - [TheBloke/deepsex-34b-GPTQ](https://huggingface.co/TheBloke/deepsex-34b-GPTQ). Based on  YI-34B-base.

**Comment by sgsdxzy** [comment]
This model is out of date, probably you should notify the model author to update it.
