### ISSUE TITLE
[Misc]: Building docker container requires insane amount of memory

### ISSUE THREAD

**Issue by mrseeker** [PygmalionAI/aphrodite-engine#350]
### Anything you want to discuss about Aphrodite.

I am trying to build a custom version of Aphrodite, however during the build of the Aphrodite engine with docker I need an insane amount of Memory and CPU. Is there a way to reduce this?

I already tried setting "MAX_JOBS=1" but that did not help.

**Comment by mrseeker** [comment]
I tried to set it at line 30 in the Dockerfile, but it still receives "Killed" by the OOM Killer.

**Comment by AlpinDale** [comment]
Perhaps it would be best to pull the aphrodite package from pypi instead of building it in the docker. `pip install aphrodite-engine==0.5.1` should do it.

**Comment by mrseeker** [comment]
I don't think the Aphrodite package supports custom-made AWS endpoints...

**Comment by puppetm4st3r** [comment]
with MAX_JOBS 2 compile ok with 64gb of ram

**Comment by AlpinDale** [comment]
Ah right this reminds me, @mrseeker , we build for all GPU architectures which may take more time and use more memory. You can try getting rid of the export for torch cuda arch list, that'll probably help.

**Comment by mrseeker** [comment]
Found out that if I changed the arch list to just include the arch that I need, then it's scaling down to almost 90Gb when compiling...
