### ISSUE TITLE
[Feature]: Add support for DBRX model

### ISSUE THREAD

**Issue by BlairSadewitz** [PygmalionAI/aphrodite-engine#385]
### 🚀 DBRX support

Just another new model. It's massive, heh.  Here's the vllm [commit](https://github.com/xjpang/vllm/commit/93605e3ab88416a4c233a878493005a3e0f2422e).  

See on [github](https://github.com/databricks/dbrx.git) and [HuggingFace](https://huggingface.co/databricks).  Here's a [non-gated link](https://huggingface.co/Undi95/dbrx-base).
["converted" model (marlin quant)](LnL-AI/dbrx-base-converted-v2-4bit-gptq-marlin-v2) (not sure what that means yet lol)

**Comment by AlpinDale** [comment]
I've had a local branch with this model implemented from day one, but didn't commit because it wasn't working with `--load-in-4bit`. Will revisit it later.

**Comment by BlairSadewitz** [comment]
Ok, oh, thanks.
