### ISSUE TITLE
[Feature]: Add support for Qwen2MoE

### ISSUE THREAD

**Issue by StableFluffy** [PygmalionAI/aphrodite-engine#387]
### 🚀 The feature, motivation and pitch

https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/qwen2_moe.py

Qwen2MoE is implemented in vLLM.

**Comment by AlpinDale** [comment]
It's added in the dev branch (RC 0.5.3). Will close this issue when merged into main.
