### ISSUE TITLE
[Feature]: actual working health endpoint

### ISSUE THREAD

**Issue by mrseeker** [PygmalionAI/aphrodite-engine#390]
### 🚀 The feature, motivation and pitch

When the backend crashes for any reason, the /health endpoint still replies with code 200. This is not preferred if the backend is actually broken, since the system relies on this endpoint to know if a reset is needed.

My proposal would be to have a global value that has the model return 500 when the backend goes into a fault state and 200 when it sends successful requests.

### Alternatives

Manually reset the server upon crash, or implement a feature to detect if the endpoint returns 500, however it does not detect which GPU is faulty.

### Additional context

When running on a faulty GPU, CUDA errors pop up followed by the system going into a full crash and being unable to respond to requests. The /health endpoint is monitored to see if the server needs a reboot.

**Comment by AlpinDale** [comment]
We have a more robust health checking at that endpoint now, have you updated to the latest main?

It'll be in the release once #388 is merged.

**Comment by mrseeker** [comment]
Does that work with completions, or only chat?
