### ISSUE TITLE
[Bug]: served-model-name is unused

### ISSUE THREAD

**Issue by mrseeker** [PygmalionAI/aphrodite-engine#399]
### Your current environment

```
Running latest docker container
```

### 🐛 Describe the bug

When trying to run the docker container with config "--served-model-name", the model name is not being used at all; instead, the original model name is being used when asking endpoint /models.

**Comment by fullstackwebdev** [comment]
... you can sneak extra params in -e "SOME=THING --servered-model-name gpt5"
