### ISSUE TITLE
PyTorch 2.1

### ISSUE THREAD

**Issue by AWAS666** [PygmalionAI/aphrodite-engine#40]
I know this released less than 24 hours ago but can this be upgraded to torch 2.1

Because otherwise the current torch installed via pip is compiled to Cuda 12.1 and not 11.8 anymore

**Comment by AlpinDale** [comment]
I've also been having this issue on runpod VMs. I tried PyTorch nightly/stable for CUDA 11.8 [as outlined by the PyTorch website](https://pytorch.org/get-started/locally/). Have you found a solution?

**Comment by AWAS666** [comment]
By adding:
```
--find-links https://download.pytorch.org/whl/torch_stable.html
torch == 2.0.1+cu118
```
in the requirements.txt I seem to be able to force it.

Buut this only seems to work when doing pip install -r requirements.txt and not when doing it over the setup file.

```
error in aphrodite-engine setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected package name at the start of dependency specifier
          --find-links https://download.pytorch.org/whl/torch_stable.html
```
