### ISSUE TITLE
[Performance]: Memory Usage Fix for gguf.

### ISSUE THREAD

**Issue by Abulhanan** [PygmalionAI/aphrodite-engine#447]
### Proposal to improve performance

Is there any way to first convert gguf model to pytorch then start the engine or ray-worker because when doing that, ray worker already uses 10gb ram and i'm left with 20gb of ram for converting, during conversion Ray crashes due to low ram, i'm using two gpus.

### Report of performance regression

Is there any way to first convert the gguf model then start ray instance??

### Your current environment (if you think it is necessary)

```text
The output of `python env.py`
```

**Comment by sgsdxzy** [comment]
Please read the doc [here](https://github.com/PygmalionAI/aphrodite-engine/wiki/8.-Quantization#gguf-dev-branch)

**Comment by Abulhanan** [comment]
okay thank you very much.
