### ISSUE TITLE
[Installation]: Upload Aphrodite v0.5.2 On Pypi.org

### ISSUE THREAD

**Issue by Abulhanan** [PygmalionAI/aphrodite-engine#451]
### Your current environment

```text
The output of `python env.py`
```

### How did you install Aphrodite?

I tried using version 0.5.2 but it's not persent there, it's needed to be updated.

**Comment by med4u** [comment]
Now with 0.5.3 please :)

**Comment by AlpinDale** [comment]
@med4u Unfortunately, PyPi has an upload file size limit of 100 MiB. New release sits at ~200 MiB so I couldn't upload until they approve my request for an extension. For now, it's hosted at our custom pypi repo. You can install it like this:

```sh
pip install -U aphrodite-engine --extra-index-url https://downloads.pygmalion.chat/whl
```

**Comment by med4u** [comment]
Thank you that works for me!
