### ISSUE TITLE
"RuntimeError: CUDA error: no kernel image is available for execution on the device" on some cloud configurations

### ISSUE THREAD

**Issue by Pyroserenus** [PygmalionAI/aphrodite-engine#49]
Full log of error in the attached text file
[colaberror.txt](https://github.com/PygmalionAI/aphrodite-engine/files/12833751/colaberror.txt)

Highlight
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Reproduction
https://colab.research.google.com/gist/Pyroserenus/22a52cc762b77bb7f814fbb200c05e74/mythogguf.ipynb#scrollTo=5fe2Ad1O5mlt

**Comment by AlpinDale** [comment]
Fixed by #52
