### ISSUE TITLE
[Feature]: Suggestion for build older versions of aphrodite engine's  docker images

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#500]
### 🚀 The feature, motivation and pitch

Currently, generating a docker image prior to the head or latest version is not so direct since the Dockerfile when doing git clone does not include the revision tag that corresponds to the release tag, in this way if I clone the code corresponding to the v0.5.0 the git clone will always download the head version and I will not be able to generate the artifact with the desired version, which will also clash with the versions of the requirements.txt packages.

This simple feature (consider adding the tag in the git clone of the Dockerfile of each release) allows us to rollback to previous dockers when the latest or the head has disabling bugs of an order of magnitude.

Additionally, it could also be considered that in the Docker repo of the artifact not only the last one is maintained but also the history of previous images remains to be able to do a docker pull of images from previous versions.

### Alternatives

manually edit the Dockerfile to build the correct desired version tag.

**Comment by AlpinDale** [comment]
We're no longer uploading to the latest tag only. Closing this issue as completed.
