### ISSUE TITLE
[Misc]: Is there a way to log the prompts content request in the console? 

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#516]
### Logging issue

I can find an environment var or setting to activate this (in prev engine versions that behaviour was by default)

regards =)

**Comment by AlpinDale** [comment]
This was disabled because of some issues regarding loguru. You can enable it by passing `--max-log-len 100000`

**Comment by puppetm4st3r** [comment]
thanks!
