### ISSUE TITLE
[Usage]: So can AMD NAVI GPUs be used with aphrodite? Which GPUs?

### ISSUE THREAD

**Issue by Nero10578** [PygmalionAI/aphrodite-engine#519]
### Your current environment

```text
The output of `python env.py`
```

### How would you like to use Aphrodite?

I want to get some AMD Navi based GPUs, but I am not quite clear on which GPUs specifically are supported. I know that the official ROCM only supports the RX 7900 series, so is that all that's supported? I am interested in getting RX 6800/6900 cards in addition to RX 7900 cards for inference.

Just hoping someone who uses AMD cards can chime in.

**Comment by AlpinDale** [comment]
Hi yes, they're supported. The easiest way is to use them through Docker. I will be updating the wiki in the next release with detailed instructions. Stay tuned!

**Comment by Nero10578** [comment]
> Hi yes, they're supported. The easiest way is to use them through Docker. I will be updating the wiki in the next release with detailed instructions. Stay tuned!

Sorry I didn't see this. Thank you!
