### ISSUE TITLE
[Usage]: How to use prefix caching?

### ISSUE THREAD

**Issue by thatname** [PygmalionAI/aphrodite-engine#520]
### Your current environment

I can not find any doc about this feature.

**Comment by sgsdxzy** [comment]
It's called `context-shift`, the name might be a bit misleading because it's not the same context shift in koboldcpp, but prefix caching.

**Comment by GodZioP** [comment]
> It's called `context-shift`, the name might be a bit misleading because it's not the same context shift in koboldcpp, but prefix caching.

So if I add --context-shift as an additional argument it should work, right?

**Comment by sgsdxzy** [comment]
Yes.
