### ISSUE TITLE
[New Model]: Please support LLama3.1 and Mistral-Nemo

### ISSUE THREAD

**Issue by BaiMoHan** [PygmalionAI/aphrodite-engine#609]
### The model to consider.

https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct

### The closest model Aphrodite already supports.

https://huggingface.co/meta-llama/Meta-Llama-3-8B
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3

### What's your difficulty of supporting the model you want?

I want to know if it is on the way😊

**Comment by AlpinDale** [comment]
Hi! Please check out our development branch `rc_054` (#481). It contains support for all the new features, including l3.1 and mistral nemo. We're getting closer to a release, but it'll take time to review (100k+ lines of code added). You can try building that branch, or use the docker image (a few days outdated):

```sh
docker run --runtime nvidia --gpus all \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    -p 2242:2242 \
    --ipc=host \
    alpindale/alpindale-openai:latest \
    --model mistralai/Mistral-Nemo-Instruct-2407 \
  -tp 3 --enable-chunked-prefill --max-model-len 32768
```

**Comment by BaiMoHan** [comment]
> Hi! Please check out our development branch `rc_054` (#481). It contains support for all the new features, including l3.1 and mistral nemo. We're getting closer to a release, but it'll take time to review (100k+ lines of code added). You can try building that branch, or use the docker image (a few days outdated):
> 
> ```shell
> docker run --runtime nvidia --gpus all \
>     -v ~/.cache/huggingface:/root/.cache/huggingface \
>     -p 2242:2242 \
>     --ipc=host \
>     alpindale/alpindale-openai:latest \
>     --model mistralai/Mistral-Nemo-Instruct-2407 \
>   -tp 3 --enable-chunked-prefill --max-model-len 32768
> ```

Good news. Nice🤩🤩🤩
