### ISSUE TITLE
[Usage]: Is the exl2 quant not supported anymore?

### ISSUE THREAD

**Issue by Authcursed** [PygmalionAI/aphrodite-engine#619]
### Your current environment

I'm using google colab for aphrodite. Like usual i use lunaris model with exl2 quant. But then I got this error after running aphrodite: aphrodite run: error: argument --quantization/-q: invalid choice: 'exl2' (choose from 'aqlm', 'awq', 'deepspeedfp', 'eetq', 'fp8', 'fbgemm_fp8', 'gguf', 'marlin', 'gptq_marlin_24', 'gptq_marlin', 'awq_marlin', 'gptq', 'quip', 'squeezellm', 'compressed-tensors', 'bitsandbytes', 'qqq', None)

Is the exl2 not supported anymore?

**Comment by Pyroserenus** [comment]
Exl2 support is currently dropped

Aplin may want to update the colab to use fp8 for the 8b/12b models as that should work well on colab now as far as I know.

Could you try to load this and edit the -q to use fp8? https://huggingface.co/Pyroserenus/L3-8B-Lunaris-v1-FP8

**Comment by AlpinDale** [comment]
Yes, we had to temporarily drop support for it. I'll update the colab notebook later, but if you need to use the old aphrodite version, please edit the notebook cell to this:

```diff
- %pip install aphrodite-engine
+ %pip install "aphrodite-engine==0.5.3" --extra-index-url https://downloads.pygmalion.chat/whl
```

Then you can run exl2 model. I do however recommend what @Pyroserenus suggested above.

**Comment by Authcursed** [comment]
Alright, thanks for the reply! I'm currently using the 0.5.3 ver to use the exl2 quant, But I'll try to use fp8
