### ISSUE TITLE
[Bug]: it's crashing.. v0.6.0

### ISSUE THREAD

**Issue by Abdulhanan535** [PygmalionAI/aphrodite-engine#621]
### Your current environment

```
ERROR:    [Errno 98] error while attempting to bind on address ('::', 2242, 0, 0): address already in use
```

### 🐛 Describe the bug

Been trying for 2 hours and no luck, tried using the host parameter too but nope, restarted everything but nope..

Command (using kaggle)

`command = [
    "aphrodite run",
    model,
    "--dtype", "float16",
    "--max-log-len", "0",
    "--gpu-memory-utilization", str(gpu_memory_utilization),
    "--max-model-len", str(context_length),
    "--tensor-parallel-size","2"
]`

**Comment by AlpinDale** [comment]
Please try a different port with `--port 2222` (recommendes) or `export APHRODITE_PORT=2222`.

**Comment by Abdulhanan535** [comment]
thanks lol..
