### ISSUE TITLE
[Misc]: Ram usage.

### ISSUE THREAD

**Issue by Abdulhanan535** [PygmalionAI/aphrodite-engine#622]
### Anything you want to discuss about Aphrodite.

using 2 t4 gpu the ram usage is 25gb average without cpu offloading, which is an issue, cuz i want to use cpu offloading and Total ram is 30gb, any way to fix this??

**Comment by AlpinDale** [comment]
Try decreasing the CPU swap. It already defaults to 4GB per GPU, but you can decrease it even further by specifying `--swap-space`. I doubt it helps that much, but give it a try.

**Comment by Abdulhanan535** [comment]
um thanks it did work, i was at 25gb and now i'm at 18, lol still a long way.

**Comment by Abdulhanan535** [comment]
decreased it to 0 and now i have 12gb ram being used 18 free yay...
