### ISSUE TITLE
[Feature]: Sliding Window Attention?

### ISSUE THREAD

**Issue by Abdulhanan535** [PygmalionAI/aphrodite-engine#637]
### 🚀 The feature, motivation and pitch

Will it be supported? just saw the new release you uploaded the post1 release.

### Alternatives

.

### Additional context

. For Gemma 2 models

**Comment by AlpinDale** [comment]
I think you mean Alternating Sliding Window Attention, which is used by gemma2 only. This requires a non-trivial change the attention and block manager code, so it'll be some time before I have the bandwidth to handle it. I'll be trying to work with the vLLM team to land this feature sometime soon. 

For now, I recommend using [tabbyAPI](https://github.com/theroyallab/tabbyAPI), as they use exllamav2 which has alternating SWA implemented.
