### ISSUE TITLE
GPTQRowParallelLinear has no attribute world_size

### ISSUE THREAD

**Issue by AWAS666** [PygmalionAI/aphrodite-engine#72]
When starting the ooba server api with gptq enabled I run into the following error:

```
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTQRowParallelLinear' object has no attribute 'world_size'
```

This has worked before, broke by pulling the most up to date git

**Comment by AlpinDale** [comment]
Hi, thanks for letting me know. The latest commit should fix it (though I didn't run a test).

**Comment by AWAS666** [comment]
That fixed it, thanks 👍
