### ISSUE TITLE
[Bug]: latest tag for docker pull did not work

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#752]
### Your current environment

docker isolated environment

### 🐛 Describe the bug

Trying to pull like:

```
dario@hightower:/media/dario/data/work/dm/dolf/server$ docker pull alpindale/aphrodite-openai
Using default tag: latest
Error response from daemon: manifest for alpindale/aphrodite-openai:latest not found: manifest unknown: manifest unknown
```

but `docker pull alpindale/aphrodite-openai:v0.6.1.post1` works w/out issues.

**Comment by AlpinDale** [comment]
Someone else reported this as well, seems like I need to push a `:latest` tag as well. I thought docker does that by default 😅

**Comment by puppetm4st3r** [comment]
hjsjsjs yes, putting the tag by hand on the dicker pull solves the problem for me!
