### ISSUE TITLE
[Bug]: Error from vllm when trying to load a quant model from docker

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#753]
### Your current environment

docker isolated environment

### 🐛 Describe the bug

same issue as this https://github.com/vllm-project/vllm/issues/754

**Comment by puppetm4st3r** [comment]
workarround:
`docker exec -it cont_name pip install -U "ray[data,train,tune,serve]"`

**Comment by AlpinDale** [comment]
This is quite a weird error, Ray shouldn't be needed by default, unless you're doing multi-node 🤔

**Comment by puppetm4st3r** [comment]
am using tp 1 pp 3, on 3x3090

**Comment by puppetm4st3r** [comment]
but installing ray inside the container solves the issue
