### ISSUE TITLE
[Bug]: KAIGenerationInputSchema has no attribute 'get'

### ISSUE THREAD

**Issue by Luke100000** [PygmalionAI/aphrodite-engine#771]
### Your current environment

[env.txt](https://github.com/user-attachments/files/17266026/env.txt)

### 🐛 Describe the bug

I installed Aphrodite via pip on a Python 3.12.5, and when using the Kobold endpoint at port 2242, I get

```
File "./aphrodite/.venv/lib/python3.12/site-packages/aphrodite/endpoints/openai/protocol.py", line 820, in check_context
    assert values.get("max_length") <= values.get(
           ^^^^^^^^^^
  File "./aphrodite/.venv/lib/python3.12/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
```

I tried downgrading Pydantic to `2.0.3` with no success.

```yaml
basic_args:
  - model: "L3-8B-Stheno-v3.2-IQ4_XS-imat.gguf"
  - served_model_name: "aphrodite/Sao10K/L3-8B-Stheno-v3.2"
  - launch_kobold_api: true
  - max_model_len: 8192
  - enable_chunked_prefill: true
  - gpu_memory_utilization: 0.95
```

**Comment by AlpinDale** [comment]
This has been fixed, and will be included in the next release. For now you can try [building from source](https://aphrodite.pygmalion.chat/pages/installation/installation.html#building-from-source).

**Comment by Luke100000** [comment]
Awesome, thanks! In addition, a lazier quickfix seems to be downgrading: `pip install "aphrodite-engine==0.6.1.post1"`
