### ISSUE TITLE
Request: Better CLI control over max CTX and rope scaling

### ISSUE THREAD

**Issue by Pyroserenus** [PygmalionAI/aphrodite-engine#78]
suggestion: adjust things so that CLI can supersede the config in order to set higher context (via the existing max ctx len) and enable rope scaling (through a new arg)

reasoning: modifying configuration files to enable higher ctx len is a less than ideal solution. at best it's awkward, at worst cloud based pip installs place the files in awkward locations and use inconsistent workspace locations.

**Comment by AlpinDale** [comment]
Added in #98 

Please set `--max-model-len` to the desired context length size and the engine will try and adjust the RoPE scaling factor to match the specified context length; the used method is Dynamic NTK.
