### ISSUE TITLE
[Bug]: The documentation page is down and empty

### ISSUE THREAD

**Issue by puppetm4st3r** [PygmalionAI/aphrodite-engine#802]
### Your current environment

N/A

### 🐛 Describe the bug

The documentation page is down and empty :(

**Comment by AlpinDale** [comment]
I thought we fixed this... @ahme-dev maybe we should just switch frameworks.

You can access the documentation at https://github.com/PygmalionAI/aphrodite-engine/tree/main/docs/pages for now

**Comment by ahme-dev** [comment]
> I thought we fixed this... @ahme-dev maybe we should just switch frameworks.
> 
> You can access the documentation at https://github.com/PygmalionAI/aphrodite-engine/tree/main/docs/pages for now

https://aphrodite.pygmalion.chat/
It works fine?

**Comment by AlpinDale** [comment]
I don't know anymore, it randomly decides to break then randomly fix itself.

**Comment by puppetm4st3r** [comment]
I can access now to the doc site

**Comment by ahme-dev** [comment]
> I don't know anymore, it randomly decides to break then randomly fix itself.

The case for @puppetm4st3r would be that he had the cached version from when it was broken. But if we ever encounter this issue again then we'll make the switch
