### ISSUE TITLE
ModuleNotFoundError: No module named 'aphrodite.common.logits'

### ISSUE THREAD

**Issue by yixuantt** [PygmalionAI/aphrodite-engine#84]
After installation and running, an error was encountered.
The installation process is normal, with no errors.
```
Traceback (most recent call last):
  File "/home/yixuan/.conda/envs/aph/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yixuan/.conda/envs/aph/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yixuan/.conda/envs/aph/lib/python3.10/site-packages/aphrodite/endpoints/openai/api_server.py", line 33, in <module>
    from aphrodite.common.logits import BiasLogitsProcessor
ModuleNotFoundError: No module named 'aphrodite.common.logits'
```

**Comment by AlpinDale** [comment]
Hi, what version are you running? 

If you installed via the embedded runtime, do:

```sh
./runtime.sh python -m pip list | grep aphrodite
```

And if not (make sure you're in the correct env first):

```sh
pip list | grep aphrodite
```

**Comment by yixuantt** [comment]
Hi, here is my version.  @AlpinDale 
```
aphrodite-engine          0.3.7
```

**Comment by AlpinDale** [comment]
Did you install via the pip package?

**Comment by AlpinDale** [comment]
Sorry for not responding - this issue is usually due to installing via the pip package and then running the engine from within the cloned repo. Please try launching the engine from another directory, or `pip uninstall aphrodite-engine` and then build from source with `pip install -e .`

Closing this as solved.
